### ISSUE TITLE
static ip iso lock issue in vsphere

### ISSUE THREAD

**Issue by jfblaine** [noseka1/openshift-auto-upi#19]
When running static ip in vsphere, i received the following message for each vm:

The guest operating system has locked the CD-ROM door and is probably using the CD-ROM, which can prevent the guest from recognizing media changes...

To get past the message, I had to manually click "Yes" to force eject in the vsphere console.  I searched for a better solution, and the following vmware doc addresses:

https://kb.vmware.com/s/article/2144053

As the article states, I tried adding the following to the customvalues section in roles/openshift_vsphere/tasks/deploy_host.yml (note the first three customvalues were already present in master branch):

```yaml
    customvalues:
      - key: guestinfo.ignition.config.data.encoding
        value: base64
      - key: guestinfo.ignition.config.data
        value: '{{ vsphere_ignition.content }}'
      - key: disk.EnableUUID
        value: 'TRUE'
      - key: cdrom.showIsoLockWarning
        value: 'FALSE'
      - key: msg.autoanswer
        value: 'TRUE'
```
This resolved the issue and allowed the playbook to complete with no manual intervention.
