### ISSUE TITLE
Setup break booting the VMs on  oVirt (RHV)

### ISSUE THREAD

**Issue by anibal-aguila** [noseka1/openshift-auto-upi#32]
Hi, this issue appear to be related with the ignition version file. some one could tell me how deal with it on oVirt
thanks in advance,

https://access.redhat.com/solutions/5680771
https://github.com/coreos/ignition/blob/master/dracut/30ignition/ignition-fetch.service

after debug the error I found **systemd** fail to load **ignition-fetch.service**

```
error at line 1 col 2: invalid character '#' looking for beginning of value
failed to acquire config: config is not valid
Ignition failed: config is not valid
```
![image](https://user-images.githubusercontent.com/49025536/112770598-a7e72600-9027-11eb-94b7-983d1af4e8f4.png)

![image](https://user-images.githubusercontent.com/49025536/112770249-1c20ca00-9026-11eb-835c-674af24a7811.png)
![image](https://user-images.githubusercontent.com/49025536/112770300-6013cf00-9026-11eb-9464-acc2b6e68858.png)

**oVirt Open Virtualization Manager
Software Version:4.4.2.6-1.el8**

openshift_install_config.yml
```
openshift_install_config:
  distribution: ocp
  version: 4.7.4
  coreos_version: 4.7.0
  name: mycluster
  base_domain: example.com
  cluster_domain: mycluster.example.com
  master_replicas: 1
  worker_replicas: 0
  ignition_url_prefix: 'http://192.168.33.3:81/openshift-auto-upi/mycluster'
  static_ips:
    enabled: False
    parameters:
      gateway: 192.168.33.1
      netmask: 255.255.255.0
      #interface: enp1s0
      #interface: ens3
      interface: eth0
      nameservers:
        - 192.168.33.1
```
